### ISSUE TITLE
Englisch Verbesserung "Home"

### ISSUE THREAD

**Issue by firtshighlander** [MinecraftVienna/mcvienna.at#2]
Ausgebesserte Sachen sind fett markiert

What do a PE teacher, a student of civil engineering, a **pilot**, a student of computer science, a **mechatronics engineer** and a student of pharmacy **have** in common?

They are **determined** to build a full-scale replica of the city **of** Vienna in the sandbox open-world-game Minecraft. 

Minecraft is a **computer game** where players can - alone or together - construct lots of creative worlds out of several different building blocks **online.** 

**Starting from the first district called "Innere Stadt", landmarks, streets, and buildings are getting built bit by bit in minute detail like the original. For that purpose satellite images, maps, as well as pictures took on site, are used. In this manner  more and more quarters of the capital city will be built during the next months and years.** 

In order to be able to coordinate better, the creative minds around **founder** Stefan Riedmann and **Server administrator** Harald Niemeczek teamed up to the **registered** association Minecraft Vienna. 

Since the beginning of 2015 Wien-Kanal is supporting this innovative **project**. Especially those parts of the Viennese canal network that can be viewed at the 3rd Man Tour, as well as parts of the Wien River are included in the three-dimensional world made **from countless blocks**.

**Comment by HNieme** [comment]
Vielen Dank,
Korrekturen wurden eingepflegt und auf der Testwebseite hochgeladen.

Ich lasse das Issue erstmal offen, vl. gibt es sonst noch Dinge zum ausbessern, die können dann gleich hier kommentiert werden.

**Comment by DrJosephMosch** [comment]
"Aufbauend auf die Korrekturen von firsthighlander meine Anmerkungen (Kommentare gekennzeichnet mit "):

What do a **PE teacher, a pilot, a bunch of students and a mechatronics engineer** have in common?
"Weniger items in der Aufzählung liest sich flüssiger.

The **determination to replicate Austrias capital city Vienna in Minecraft, the worlds most played open world sandbox game.**
"Determination funktioniert als Nomen besser. 
"Das Ende des Satzes wurde umstrukturiert.

"Den Zwischensatz würde ich komplett weglassen.

Starting from **the historic city centre, all of Viennas famous** landmarks, streets and buildings are getting built **block by block**. **To manage such a challenging task, the team makes use of official land plans, sattelite images as well as selfmade pictures.** In this manner more and more **parts** of the capital city **are being built in** the next months and years.
"Englischsprachige interressiert es eher nicht, wie die Bezirke heißen. 
"Block by Block ist selbsterklärend.
"Satz umstrukturiert
"Richtige Zeitform

"Satz weglassen. Die info ist für internationale fans uninterressant.

**In 2015 a parnership with Wien-Kanal, the city authority responsible for the sewers, was established to promote the 3rd man tour. Now you can revisit the scenes of the famous movie "the 3rd man" both in real life and in Minecraft.**
"Partnership klingt besser
"Kanal = uninterressant, 3rd man = weniger uninterressant

**Comment by HNieme** [comment]
wurde umgesetzt.

**Comment by firtshighlander** [comment]
The determination to replicate **Austria's** capital city Vienna in Minecraft, the **world's** most played open world sandbox game.

Bei Austria und world hat nur jeweils das Apostroph gefehlt.

Edit: Bei den Feldern zum Umstellen der Sprache sollte Deutsch bzw. Englisch groß geschrieben sein.

**Comment by HNieme** [comment]
Danke, 
Ich habe das build a full-scale drinnengelassen, klingt imho besser:
**The determination to build a full-scale replica of Austria's capital city Vienna in Minecraft, the world's most played open world sandbox game.**

"Deutsch" und "English" sind jetzt überall groß geschrieben, gehört "English" sicher groß geschrieben?

**Comment by firtshighlander** [comment]
Ja, gehört groß geschrieben.
