### ISSUE TITLE
Galerie

### ISSUE THREAD

**Issue by DrJosephMosch** [MinecraftVienna/mcvienna.at#3]
Zwei Issues:

1. Die Englisch-Übersetzungen sind teilweise sinnentleert, Beispiel "Horticulture high-rise" Bitte komplett weglassen. Achtung: Oft beschreiben die Dateinamen nicht adequat den Inhalt, bitte auch in der Deutschen Version aufpassen.

2. Bitte die Fotos generell aussortieren und absteigend nach Datum sortieren.

**Comment by HNieme** [comment]
ad 1) "Horticulture Skyscraper (Gartenbauhochhaus)" ist eine direkte Übersetzung von Gartenbauhochhaus, mit dem deutschen Namen in Klammern als Erklärung dazu. "high-rise" kommt eigentlich in den Übersetzungen gar nicht vor.
In den alt-tags (solltest Du den Code angesehen haben) sind Stichwörter vorhanden, diese sind nur für Suchmaschinen bestimmt, daher von den Wortzusammenhängen sinnentleert.

ad 2) Aussortieren nach welchen Kriterien?
Das Sortieren nach Datum ist aufgrund der Art und Weise, wie die Bilder in Spalten dargestellt werden kaum möglich - verändert man die Darstellungsbreite, fallen Spalten untereinander -> Ordnung nach Datum nur in einer Bildschirmbreite möglich und daher relativ sinnlos.

**Comment by DrJosephMosch** [comment]
1. Dann steht da halt Skyscraper statt high-rise, die Übersetzung ist genauso sinnbefreit. Google den Begriff mal und du siehst a) was ein Horticultur Skyscraper ist und b) dass das Gartenbauhochhaus in den Google Ergebnissen nicht vorkommt.

2. Hast du dir die Bildergalerie einmal angeschaut?Die ist voller Duplikate, ewig alter Bilder und langweiligen leeren Bildern. Siehe http://imgur.com/a/0Q6pT als Anfang
Wenn die Ordnung nach Datum mit dem System der Gallerie nicht möglich ist, dass ist das System sinnlos und gehört geändert.

**Comment by HNieme** [comment]
1.1. Dass mit horticulture skyscraper vertical farms bezeichnet werden war mir nicht klar, sorry. Fällt aber mit 2. sowieso weg.
1.2. Natürlich kommt das Bild (und andere unserer Bilder) in der Bildersuche von Google vor: https://www.google.at/search?q=gartenbauhochhaus+minecraft&source=lnms&tbm=isch&sa=X&ved=0ahUKEwirrMGGm8zVAhWHxRQKHYzSAHMQ_AUICigB&biw=1920&bih=961#imgrc=vqYu_0hglJRNrM:
und
https://www.google.at/search?biw=1920&bih=961&tbm=isch&sa=1&q=gartenbauhochhaus+wien&oq=gartenbauhochhaus+wien&gs_l=psy-ab.3...91366.91836.0.92396.4.4.0.0.0.0.71.269.4.4.0....0...1.1.64.psy-ab..0.0.0.kseOLCaSi_0#imgrc=vqYu_0hglJRNrM:


2. Bilder (fast) alle lt. imgur-Bild entfernt. Nur weil ein Gebäude in unterschiedlichen Perspektiven abgebildet ist, heißt das meiner Meinung nicht, dass es ein doppeltes Bild ist.

Ich möchte daran erinnern, dass die Bilder, die "langweilig" sind, von Dir stammen und nach Deiner Anweisung in die Webseite eingepflegt wurden.

Nachdem Du ja ausschließlich aktuelle Bilder in der Galerie haben willst, sehe ich keinen Bedarf nach einer Ordnung nach Datum (und damit einer aufwändigen Änderung des Systems). Außerdem habe ich kein Interesse daran, für jedes Bild zu recherchieren, wann es gemacht wurde und danach neu zu sortieren. Das ist für mich wieder einen Tag Arbeit, den ich wesentlich sinnvoller investieren könnte.

**Comment by HNieme** [comment]
Übrigens: Teilweise wurden als veraltet markierte Bilder durch neue ersetzt.

**Comment by DrJosephMosch** [comment]
ad 1.2) Wenn du "horticulture skyscraper" auf google suchst, kommt das Gartenbauhochhaus nicht in den Ergebnissen. Manchmal kommt es mir so vor, als würdest du absichtlich versuchen mich misszuverstehen.

ad 2) Der Foto-Ordner auf unserer Google Drive ist für alle freigegeben und wird von mehreren Personen befüllt. Nicht jedes Foto im Ordner ist automatisch websitetauglich. Etwas Eigenverantwortung beim hochladen wäre wünschenswert.

Es geht mir nicht darum, ausschließlich aktuelle Bilder zu haben, sondern ewig alte Bilder von halbfertigen Bauten wegzunehmen.
Was ich aber absolut will, ist, dass neu hochgeladene Bilder nach vor gereit sind. Und deine "Recherche" wann du welches Bild ab jetzt hochladest sollte dich wirklich nicht überfordern. Als Entgegenkommen werde ich alle folgenden Render mit Dateinamen JJJJ-MM-TT-_________ benennen.
Anstatt hier rumzumaulen könntest du auch andere Lösungsmöglichkeiten suchen, zum Beispiel ein Sortieren der Bilder nach anderen Kriterien, z.B nach dem Dateinamen, was bei oben beschriebener Änderung auch einer Sortierung nach Datum gleichkommt.

**Comment by HNieme** [comment]
ad 1) nein, eigentlich nicht. Ein Auftrauchen unseres Bildes unter "horticulture skyscraper" in den Google Suchergebnissen wäre (mangels veröffentlichter Version mit dieser Übersetzung und daher fehlender Indexierung durch Google) gar nicht möglich.

ad 2) Ok, bitte benenne die Bilder in Zukunft so, das wäre eine große Hilfe.

Die aktuellen Bilder belasse ich in der Ordnung, neue Bilder werden nun immer an die "Spitze" hinzugefügt und durch dann vorhandenes Datum im Dateinamen sortiert.
